version: "3.5"
# You should be able to find & replace all instances of syncthing with 
# your actual_service_name. Then you just need address any places that 
# typically need changes (designated by comments)

networks:
  syncthing:

volumes:
  syncthing:

#secrets:
#  syncthing_admin_password:
#    name: ${STACK_NAME:-technocore}_syncthing_admin_password
#    external: true

services:
  # Uncomment this if Traefik will be used for routing traffick to this service.
  ingress:
    networks:
      - syncthing

  syncthing:
    deploy:
      labels:
        - traefik.frontend.rule=$SYNCTHING_ROUTING_LABEL
        - traefik.frontend.priority=$SYNCTHING_ROUTING_LABEL_PRIORITY
        - traefik.port=8384
      #  - ${TRAEFIK_BASIC_AUTH}
        - traefik.enable=true
        # You'll need to set applicaiton's port here.
        - traefik.tags=ingress 
        - traefik.docker.network=${STACK_NAME:-technocore}_syncthing
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      #resources:
      #  limits:
      #    memory: 128M
      #  reservations:
      #    memory: 64M
    #environment:
    #  # Sometimes you have to pass in ${DOMAIN} to enable the correct link paths to be generated.
    #  # Othertimes you can use http:// or https:// for the website. Weird trick.
    #  - ADMIN_USER=${ADMIN_USER}
    image: syncthing/syncthing # ${image_provider:-scififarms}/technocore-syncthing:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - syncthing
    #secrets:
    #  - source: syncthing_syncthing_db_password
    #    target: syncthing_db_password
    volumes:
      - syncthing:/var/syncthing 
